# Generated by Django 5.2.1 on 2025-06-10 10:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Преподаватель'), ('student', 'Студент')], default='student', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивный')),
                ('group_number', models.IntegerField(blank=True, null=True, verbose_name='Номер группы')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('scores', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('test', models.BooleanField(default=False)),
                ('date_of_the_test', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_test', models.TimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='Группы, к которым принадлежит пользователь.', related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Разрешения, которые назначены пользователю.', related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start_theory', 'Начал теоретический тест'), ('start_practice', 'Начал практический тест'), ('register_student', 'Зарегистрирован студент'), ('login', 'Вход в систему'), ('training', 'Обучение'), ('testing', 'Тестирование')], max_length=50, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('difficulty', models.CharField(blank=True, max_length=20, null=True, verbose_name='Сложность')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('user_time', models.IntegerField(blank=True, null=True, verbose_name='Время ученика (сек)')),
                ('norm_time', models.IntegerField(blank=True, null=True, verbose_name='Нормативное время (сек)')),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.user', verbose_name='Пользователь')),
            ],
        ),
    ]
