# Generated by Django 5.2.1 on 2025-06-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_user_is_active_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activation_token_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_active',
        ),
    ]
