# Generated by Django 5.2.1 on 2025-06-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
