# Generated by Django 5.2.1 on 2025-06-05 11:02

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_user_activation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_the_test',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='group_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер группы'),
        ),
        migrations.AddField(
            model_name='user',
            name='scores',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='time_test',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
