# Generated by Django 5.2.1 on 2025-06-05 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_remove_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start_theory', 'Начал теоретический тест'), ('start_practice', 'Начал практический тест'), ('register_student', 'Зарегистрирован студент'), ('login', 'Вход в систему')], max_length=50, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.user', verbose_name='Пользователь')),
            ],
        ),
    ]
