# Generated by Django 5.2.1 on 2025-06-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Сложность'),
        ),
    ]
