# Generated by Django 5.2.1 on 2025-06-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_activitylog_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
    ]
